version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www
      - ./nginx/hosts:/etc/nginx/conf.d
    depends_on:
      php:
        condition: service_healthy

  php:
    build: ./php
    volumes:
      - ./html:/var/www
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 1s
