apiVersion: v1 
kind: Namespace
metadata:
 name: cicd
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: gitlab-data
 namespace: cicd
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 4Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: gitlab-config
 namespace: cicd
spec:
 accessModes:
   - ReadWriteOnce
 resources:
   requests:
     storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: gitlab
 namespace: cicd
 labels:
   app: gitlab
spec:
 selector:
   matchLabels:
     app: gitlab
 template:
   metadata:
     labels:
       app: gitlab
   spec:
     containers:
     - image: gitlab/gitlab-ce:13.11.3-ce.0
       name: gitlab
       volumeMounts:
       - name: gitlab-data
         mountPath: /var/opt/gitlab
       - name: gitlab-config
         mountPath: /etc/gitlab
       ports:
       - containerPort: 80
       - containerPort: 22
     volumes:
     - name: gitlab-data
       persistentVolumeClaim:
         claimName: gitlab-data
     - name: gitlab-config
       persistentVolumeClaim:
         claimName: gitlab-config
---
apiVersion: v1
kind: Service
metadata:
 name: gitlab
 namespace: cicd
spec:
 type: LoadBalancer
 selector:
   app: gitlab
 ports:
   - name: http
     protocol: TCP
     port: 80
     targetPort: 80
   - name: ssh
     protocol: TCP
     port: 22
     targetPort: 22
